### ISSUE TITLE
what is the usage of LENGTH

### ISSUE THREAD

**Issue by jkwebster** [indeedeng/proctor#14]
Hi,I really can not understand how to use the "lenght" in range block,in my opinions,the " length" should be the probability of getting the bucketvalue,just like the following example,if I run it 100 times,under ideal conditions I will get "A" 20 times and "B" 80 times,is it right? 
======================================
"allocations": [
{
    "ranges": [
    {
        "length": 0.2,
        "bucketValue": A
    },
    {
        "length": 0.8,
        "bucketValue": B
    }
    ]
}
]

**Comment by youknowjack** [comment]
@jkwebster sorry for the delay in answering your question. The length describes the size of the allocation to which it belongs. If the first allocation is 0.2, as in your example, then its distribution covers the first 20% of the full integer range. For tests of type RANDOM, a random number is generated on each evaluation, and if it falls in that range, then you'll be in the first bucket (and happens approximately 20 times out of 100, as you suggest). For other test types that are based on an ID, a uniform hash of the ID into the integer range is used in the same way, meaning that roughly 20% of IDs will fall into that bucket.

I hope this explanation helps. This slide might help visualize it:
http://www.slideshare.net/indeedeng/indeed-eng-2013-1002-proctor/63
