### ISSUE TITLE
Unable to create test-definitions using Proctor Webapp

### ISSUE THREAD

**Issue by SaharshSingh97** [indeedeng/proctor#50]
after deploying Proctor Webapp, there are a few console error when opening the Webapp on browser. The test-definitions are not created after filling the details, and on clicking save button, the job-ids would fail.
attaching the console errors:
<img width="1440" alt="Screenshot 2020-03-03 at 1 32 13 PM" src="https://user-images.githubusercontent.com/54524435/75765009-cfa48580-5d64-11ea-96a7-6de29a292a2e.png">
attaching the consoleOutput for the first error:
[consoleOutput.txt](https://github.com/indeedeng/proctor/files/4280659/consoleOutput.txt)
and the console output for the 2nd error 
<img width="1438" alt="Screenshot 2020-03-03 at 1 25 10 AM" src="https://user-images.githubusercontent.com/54524435/75765163-12fef400-5d65-11ea-9b11-c6f19aaadf5a.png">

Adding reference for the same query raised on google groups
https://groups.google.com/forum/#!category-topic/indeedeng-proctor-users/all-questions/ceGOE34njAw

**Comment by taitori** [comment]
Hello, thanks for reporting the issue.

I tried to reproduce the issue in my machine but couldn't. Could you provide more detailed steps about how to reproduce it?

Thanks.

**Comment by SaharshSingh97** [comment]
followed the steps mentioned here in the link: https://github.com/indeedeng/proctor/tree/master/proctor-webapp

after 4th step, we open the webapp on browser, and the console errors are shown as above.

**Comment by taitori** [comment]
I identified the reason of this issue. In proctor, we compile JS files using python (https://github.com/indeedeng/proctor/blob/master/proctor-webapp/pom.xml), and this only works well with Python2 now. So the workaround should be switching Python version from 3 to 2. We'll fix this issue as soon as possible.

Thanks!

**Comment by isozuka** [comment]
Hi @SaharshSingh97,
We have released the latest proctor-webapp with the fix of this issue. It no longer depends on the python version.  
Please try it out.
Thanks.
