### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by pawitp** [indeedeng/proctor#65]
The README links to https://engineering.indeedblog.com/blog/2013/05/indeedeng-data-driven-product-design-slides-video/ which is no longer working.

**Comment by madanalogy** [comment]
Link text "data driven product design" could potentially be fixed by pointing to one of the following URLs:
- https://engineering.indeedblog.com/talks/data-driven-product-design/
- https://medium.com/indeed-engineering/data-driven-product-design-18c6bfe1cc1c

**Comment by taitori** [comment]
Thanks for reporting. I found the snapshot of the original link ([web archive](https://web.archive.org/web/20201021095148/https://engineering.indeedblog.com/blog/2013/05/indeedeng-data-driven-product-design-slides-video/). We can update the link to the first one as it has the same video linked.
